### ISSUE TITLE
Pull most of info from app

### ISSUE THREAD

**Issue by jduss4** [open-oni/plugin_map#1]
Rather than listing the title names, etc, instead use the db records to grab each city's titles and match that against lat / long to generate the json being used?

**Comment by jechols** [comment]
I'm going to try and move forward a bit on this - if we can use the "places" database, and get people to put lat/long in there on their own, this could work well.

I'll file a ticket to make this automated when lat/long aren't already there unless I find an amazing way to do this.  (It looks like there was an attempt to do this in a "link_places" command, but it isn't working for me)

**Comment by jechols** [comment]
Damn, I'm good
